// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Aggregated input context for a single Wizard GA run. Built once by the WizardContextBuilder before evolution starts.
/// All collections are read-only during the GA loop. Scheduling-Constants are loaded from settings up-front.
/// </summary>

namespace Klacks.ScheduleOptimizer.Models;

public class CoreWizardContext
{
    public DateOnly PeriodFrom { get; init; }

    public DateOnly PeriodUntil { get; init; }

    public IReadOnlyList<CoreAgent> Agents { get; init; } = [];

    public IReadOnlyList<CoreShift> Shifts { get; init; } = [];

    public IReadOnlyList<CoreContractDay> ContractDays { get; init; } = [];

    public IReadOnlyList<CoreScheduleCommand> ScheduleCommands { get; init; } = [];

    public IReadOnlyList<CoreShiftPreference> ShiftPreferences { get; init; } = [];

    public IReadOnlyList<CoreBreakBlocker> BreakBlockers { get; init; } = [];

    public IReadOnlyList<CoreLockedWork> LockedWorks { get; init; } = [];

    /// <summary>Unlocked existing Works in the period; veto source for Stage 0 only, never lifted into the genome.</summary>
    public IReadOnlyList<CoreExistingWorkBlocker> ExistingWorkBlockers { get; init; } = [];

    /// <summary>
    /// Breaks (Vacation/Sick/Absence) on the days adjacent to the period (within ContextDaysBefore/After of the request).
    /// Provided for boundary-constraint validators (MaxConsecutiveDays/MinRestHours/MinRestDays) to detect runs that
    /// cross period boundaries. The GA never plans these days, never scores them, never mutates them.
    /// </summary>
    public IReadOnlyList<CoreBreakBlocker> BoundaryBreakBlockers { get; init; } = [];

    /// <summary>
    /// LockedWorks (Confirmed/Approved/Closed) on the days adjacent to the period. Same purpose as BoundaryBreakBlockers
    /// — boundary-only constraint validation, never lifted into the genome.
    /// </summary>
    public IReadOnlyList<CoreLockedWork> BoundaryLockedWorks { get; init; } = [];

    /// <summary>
    /// Unlocked existing Works on the days adjacent to the period. Used for the same boundary-only purpose.
    /// </summary>
    public IReadOnlyList<CoreExistingWorkBlocker> BoundaryExistingWorkBlockers { get; init; } = [];

    public int SchedulingMaxConsecutiveDays { get; init; } = 6;

    public double SchedulingMinPauseHours { get; init; } = 11;

    public double SchedulingMaxOptimalGap { get; init; } = 2;

    public double SchedulingMaxDailyHours { get; init; } = 10;

    public double SchedulingMaxWeeklyHours { get; init; } = 50;

    /// <summary>Scenario isolation token; propagated through all DB writes generated by this run.</summary>
    public Guid? AnalyseToken { get; init; }
}
