// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/// <summary>
/// Aggregated input context for a single Wizard GA run. Built once by the WizardContextBuilder before evolution starts.
/// All collections are read-only during the GA loop. Scheduling-Constants are loaded from settings up-front.
/// </summary>

namespace Klacks.ScheduleOptimizer.Models;

public class CoreWizardContext
{
    public DateOnly PeriodFrom { get; init; }

    public DateOnly PeriodUntil { get; init; }

    public IReadOnlyList<CoreAgent> Agents { get; init; } = [];

    public IReadOnlyList<CoreShift> Shifts { get; init; } = [];

    public IReadOnlyList<CoreContractDay> ContractDays { get; init; } = [];

    public IReadOnlyList<CoreScheduleCommand> ScheduleCommands { get; init; } = [];

    public IReadOnlyList<CoreShiftPreference> ShiftPreferences { get; init; } = [];

    public IReadOnlyList<CoreBreakBlocker> BreakBlockers { get; init; } = [];

    /// <summary>
    /// Seasonal daily forbidden-time windows (K16). Each carries the fully resolved set of restricted shift
    /// ids for its group tag (empty tag = all period shifts). The Stage-0 filter vetoes any slot overlapping
    /// such a window ALWAYS - hard, like a break blocker, even when the compliance enforcement mode is only
    /// warn - so the GA lays split shifts automatically around the window. Empty means no K16 rule applies.
    /// </summary>
    public IReadOnlyList<CoreRestrictedTimeWindow> RestrictedTimeWindows { get; init; } = [];

    public IReadOnlyList<CoreLockedWork> LockedWorks { get; init; } = [];

    /// <summary>
    /// Assignments from the last accepted plan of the previous period, already mapped onto this period's
    /// date axis. Seeds the warm-start population strategy. Empty means no warm-start (new group / no prior plan).
    /// </summary>
    public IReadOnlyList<CoreWarmStartAssignment> WarmStartAssignments { get; init; } = [];

    /// <summary>Unlocked existing Works in the period; veto source for Stage 0 only, never lifted into the genome.</summary>
    public IReadOnlyList<CoreExistingWorkBlocker> ExistingWorkBlockers { get; init; } = [];

    /// <summary>
    /// Breaks (Vacation/Sick/Absence) on the days adjacent to the period (within ContextDaysBefore/After of the request).
    /// Provided for boundary-constraint validators (MaxConsecutiveDays/MinRestHours/MinRestDays) to detect runs that
    /// cross period boundaries. The GA never plans these days, never scores them, never mutates them.
    /// </summary>
    public IReadOnlyList<CoreBreakBlocker> BoundaryBreakBlockers { get; init; } = [];

    /// <summary>
    /// LockedWorks (Confirmed/Approved/Closed) on the days adjacent to the period. Same purpose as BoundaryBreakBlockers
    /// — boundary-only constraint validation, never lifted into the genome.
    /// </summary>
    public IReadOnlyList<CoreLockedWork> BoundaryLockedWorks { get; init; } = [];

    /// <summary>
    /// Unlocked existing Works on the days adjacent to the period. Used for the same boundary-only purpose.
    /// </summary>
    public IReadOnlyList<CoreExistingWorkBlocker> BoundaryExistingWorkBlockers { get; init; } = [];

    public int SchedulingMaxConsecutiveDays { get; init; } = 6;

    public double SchedulingMinPauseHours { get; init; } = 11;

    public double SchedulingMaxOptimalGap { get; init; } = 2;

    public double SchedulingMaxDailyHours { get; init; } = 10;

    public double SchedulingMaxWeeklyHours { get; init; } = 50;

    /// <summary>Scenario isolation token; propagated through all DB writes generated by this run.</summary>
    public Guid? AnalyseToken { get; init; }

    /// <summary>
    /// Precomputed (agent, shift, date) triples the agent must NOT receive because it lacks a
    /// mandatory qualification the shift requires. Built once by the bridge layer via the shared
    /// eligibility matcher. Empty means no qualification gating at all — everyone is eligible — so
    /// plans without mandatory shift qualifications behave exactly as before.
    /// </summary>
    public IReadOnlySet<(string AgentId, Guid ShiftId, DateOnly Date)> IneligibleAssignments { get; init; }
        = new HashSet<(string, Guid, DateOnly)>();

    /// <summary>
    /// True if the agent may hold the given shift on the date — i.e. the triple is not flagged
    /// ineligible. With an empty set the check is a no-op and every agent is eligible.
    /// </summary>
    public bool IsEligible(string agentId, Guid shiftId, DateOnly date)
        => IneligibleAssignments.Count == 0
            || !IneligibleAssignments.Contains((agentId, shiftId, date));

    private Dictionary<(string AgentId, DateOnly Date), bool>? _worksOnDateLookup;

    /// <summary>
    /// Per-date contract availability: true/false when a CoreContractDay exists for the pair
    /// (false covers days without an active contract), null when no per-date information exists —
    /// callers then fall back to the agent's static weekday flags. Lazily built once per run.
    /// </summary>
    public bool? WorksOnDate(string agentId, DateOnly date)
    {
        if (ContractDays.Count == 0)
        {
            return null;
        }

        _worksOnDateLookup ??= BuildWorksOnDateLookup();
        return _worksOnDateLookup.TryGetValue((agentId, date), out var worksOnDay)
            ? worksOnDay
            : null;
    }

    private Dictionary<(string, DateOnly), bool> BuildWorksOnDateLookup()
    {
        var lookup = new Dictionary<(string, DateOnly), bool>(ContractDays.Count);
        foreach (var day in ContractDays)
        {
            lookup[(day.AgentId, day.Date)] = day.WorksOnDay;
        }

        return lookup;
    }
}
